force-app/main/default/objects/Transaction_Log__c/Transaction_Log__c.object-meta.xml
<CustomObject>
    <description>Object to handle transaction error logs</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>TL-{0000000}</displayFormat>
        <label>Transaction Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Trigger/Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <description>Actual error that happened in the transaction</description>
    <label>Error Log</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Exception_Time__c.field-meta.xml
<CustomField>
    <fullName>Exception_Time__c</fullName>
    <description>Time at which exception occurred</description>
    <label>Exception Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>Method in which the transaction error happened</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TransactionLogHandler.cls
/*
    @Author : Sidharth Pushp
    @BuiltDate : 26th April, 2022
    @Project : VMware Assignment
    @Description : This class is to create the Transaction Log record if any Error or Exception occurs while processing !!
*/
public class TransactionLogHandler{
    
    /*
        @Author : Sidharth Pushp
        @BuildDate : 26th April, 2022
        @Description : Handles the exception related to the class by creating new transaction log record
        @Params : System.Exception ex , String processName
        @Return: void
    */
    public static void doHandleException( System.Exception ex , String processName ) {
        
        Transaction_Log__c transactionLog = new Transaction_Log__c(
            Error_Log__c = ex.getStackTraceString() + '<br/>' + ex.getMessage() + '<br/>' + ex.getCause() + ' <br/>' + ex.getTypeName(),
            Exception_Time__c = System.Now(),
            Process_Name__c = processName,
            Class_Name__c = processName
        );
        
        if ( Schema.sObjectType.Transaction_Log__c.isCreateable() ) {
            insert transactionLog;
        }
    }
}