force-app/main/default/objects/Author__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <description>Age of author</description>
    <label>Age</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/CountryOfOrigin__c.field-meta.xml
<CustomField>
    <fullName>CountryOfOrigin__c</fullName>
    <description>Country of origin of author</description>
    <label>Country of Origin</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First name of author</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last name of author</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the book</description>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Fiction</fullName>
            </value>
            <value>
                <fullName>Historical fiction</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Non fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language of the book</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/PublishingDate__c.field-meta.xml
<CustomField>
    <fullName>PublishingDate__c</fullName>
    <description>Publishing date of the book</description>
    <label>Publishing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/PublishingHouse__c.field-meta.xml
<CustomField>
    <fullName>PublishingHouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publishing house of the book</description>
    <label>Publishing House</label>
    <referenceTo>PublishingHouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/BookAuthor__c.object-meta.xml
<CustomObject>
    <description>Junction object between book and author</description>
    <label>Book&apos;s Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book&apos;s Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BookAuthor__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipName>Author_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipName>Book_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PublishingHouse__c/PublishingHouse__c.object-meta.xml
<CustomObject>
    <label>Publishing House</label>
    <nameField>
        <label>Publishing House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishing House</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PublishingHouse__c/fields/HeadquarterCountry__c.field-meta.xml
<CustomField>
    <fullName>HeadquarterCountry__c</fullName>
    <label>Headquarter Country</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PublishingHouse__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the publishing house</description>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PublishingHouse__c/fields/YearOfEstablishment__c.field-meta.xml
<CustomField>
    <fullName>YearOfEstablishment__c</fullName>
    <label>Year of Establishment</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublisherBookDetailClass_Test.cls
/*
    @Author         : Sidharth Pushp
    @BuiltDate      : 24th April, 2022
    @Project        : VMware Assignment
    @Description    : This test class is used to provide testing coverage for PublisherBooksDetailsClassBSO class
*/
@isTest(seeAllData = false)
public class PublisherBookDetailClass_Test {
    
    /*
        @Author         : Sidharth Pushp
        @BuildDate      : 22nd April, 2022
        @Description    : Setup the test data for validating the PublisherBooksDetailsClassBSO class
        @Params         : none
        @Return         : none
    */
    @TestSetup
    public static void setupData() {
        // Insert 500 records for the publishing house
        List<PublishingHouse__c> pubHouseList = new List<PublishingHouse__c>();
        for ( Integer phCount = 0; phCount < 500; phCount++ ) {
            pubHouseList.add(
                new PublishingHouse__c(
                    Name                    = 'Test Publishing House ' + (phCount + 1),
                    Title__c                = 'Test Publishing House ' + (phCount + 1),
                    HeadquarterCountry__c   = 'England',
                    YearOfEstablishment__c  = String.valueOf(1842 + phCount + 1)
                )
            );
        }
        insert pubHouseList;
        
        // Insert 500 book records data
        List<Book__c> booksList = new List<Book__c>();
        List<String> booksGenre = new List<String> { 'Comedy' , 'Science Fiction' , 'Romance' , 'Novel' , 'Horror' };
        Integer bookGenreListLength = booksGenre.size();
        
        for ( Integer bookCount = 0; bookCount < 500; bookCount++ ) {
            Double randomNumber = Math.random();
            Integer randomIndex =  ( randomNumber * ( bookGenreListLength - 1 )).intValue(); 
            booksList.add(
                new Book__c(
                    Name                = 'Book ' + (bookCount + 1),
                    Genre__c            = booksGenre[randomIndex],
                    PublishingDate__c   = Date.newInstance(1910, 01, 01).addMonths(randomIndex),
                    Language__c         = 'English',
                    PublishingHouse__c  = pubHouseList[randomIndex].Id
                )
            );
        }
        insert booksList;
        
        // Insert 500 author records data
        List<Author__c> authorList = new List<Author__c>();
        for ( Integer authorCount = 0; authorCount < 500; authorCount++ ) {
            authorList.add(
                new Author__c(
                    Name                = 'Auhtor ' + (authorCount + 1),
                    FirstName__c        = 'Auhtor',
                    LastName__c         = String.valueOf(authorCount + 1),
                    CountryOfOrigin__c  = 'England',
                    Age__c              = 67
                )
            );
        }
        insert authorList;
        
        // Insert 500 Book's Author junction object records data
        List<BookAuthor__c> bookAuthorList = new List<BookAuthor__c>();
        for ( Integer baCount = 0; baCount < 500; baCount++ ) {
            bookAuthorList.add(
                new BookAuthor__c(
                    Book__c             = booksList[baCount].Id,
                    Author__c           = authorList[baCount].Id
                )
            );
        }
        insert bookAuthorList;
    }

    @IsTest
    static void fetchBooksToShowOnPublisherTest() {
        Test.startTest();

            BookAuthor__c bookAuthor = [
                SELECT 
                    Id, Author__c, Book__c, Author__r.FirstName__c, Author__r.LastName__c, Book__r.Name, 
                    Book__r.Genre__c, Book__r.Language__c, Book__r.PublishingDate__c, Book__r.PublishingHouse__c 
                FROM BookAuthor__c
                LIMIT 1
            ];
            PublisherBooksDetailsClassBSO.fetchBooksToShowOnPublisher(bookAuthor.Book__r.PublishingHouse__c);
            PublisherBooksDetailsClassBSO.fetchBooksToShowOnPublisher('');

            Book__c book = [
                SELECT
                    Id, Name, Genre__c
                FROM Book__c
                WHERE Id =: bookAuthor.Book__c 
                LIMIT 1
            ];

            // Assert for genre of book from book author
            System.assertEquals( bookAuthor.Book__r.Genre__c , book.Genre__c );

        Test.stopTest();
    }
}