force-app/main/default/objects/Author__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First name of author</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last name of author</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the book</description>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Fiction</fullName>
            </value>
            <value>
                <fullName>Historical fiction</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Non fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language of the book</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/PublishingDate__c.field-meta.xml
<CustomField>
    <fullName>PublishingDate__c</fullName>
    <description>Publishing date of the book</description>
    <label>Publishing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/PublishingHouse__c.field-meta.xml
<CustomField>
    <fullName>PublishingHouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Publishing house of the book</description>
    <label>Publishing House</label>
    <referenceTo>PublishingHouse__c</referenceTo>
    <relationshipLabel>Books</relationshipLabel>
    <relationshipName>Books</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/BookAuthor__c.object-meta.xml
<CustomObject>
    <description>Junction object between book and author</description>
    <label>Book&apos;s Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book&apos;s Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BookAuthor__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipName>Author_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipName>Book_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PublishingHouse__c/PublishingHouse__c.object-meta.xml
<CustomObject>
    <label>Publishing House</label>
    <nameField>
        <label>Publishing House Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publishing House</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PublisherBooksDetailsClassDAO.cls
/*
    @Author         : Sidharth Pushp
    @BuiltDate      : 22nd April, 2022
    @Project        : VMware Assignment
    @Description    : This DAO class is used to provide soql results to PublisherBooksDetailsClassBSO class
*/
public class PublisherBooksDetailsClassDAO {
    
    /*
        @Author         : Sidharth Pushp
        @BuildDate      : 22nd April, 2022
        @Description    : Get all books published by the publishing house from BookAuthor junction object.
                          Getting it from juntion object will make things work in just one query.
        @Params         : String publisherId
        @Return         : List<BookAuthor__c>
    */
    public static List<BookAuthor__c> getBooksOnPublisher( String publisherId ) {
        return [
            SELECT 
                Id, Author__c, Book__c, Author__r.FirstName__c, Author__r.LastName__c, Book__r.Name, 
                Book__r.Genre__c, Book__r.Language__c, Book__r.PublishingDate__c 
            FROM BookAuthor__c 
            WHERE 
                Book__r.PublishingHouse__c =: publisherId 
            LIMIT 50000
        ];
    }
}