force-app/main/default/objects/Author__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>First name of author</description>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Author__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>Last name of author</description>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <description>Genre of the book</description>
    <label>Genre</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Fiction</fullName>
            </value>
            <value>
                <fullName>Historical fiction</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Mystery</fullName>
            </value>
            <value>
                <fullName>Non fiction</fullName>
            </value>
            <value>
                <fullName>Novel</fullName>
            </value>
            <value>
                <fullName>Romance</fullName>
            </value>
            <value>
                <fullName>Science fiction</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Tragedy</fullName>
            </value>
            <value>
                <fullName>Poetry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Book__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <description>Language of the book</description>
    <label>Language</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Book__c/fields/PublishingDate__c.field-meta.xml
<CustomField>
    <fullName>PublishingDate__c</fullName>
    <description>Publishing date of the book</description>
    <label>Publishing Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/BookAuthor__c.object-meta.xml
<CustomObject>
    <description>Junction object between book and author</description>
    <label>Book&apos;s Author</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Book&apos;s Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Authors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BookAuthor__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <label>Author</label>
    <referenceTo>Author__c</referenceTo>
    <relationshipName>Author_Books</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BookAuthor__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipName>Book_Authors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PublisherBooksDetailsClassBSO.cls
/*
    @Author         : Sidharth Pushp
    @BuiltDate      : 22nd April, 2022
    @Project        : VMware Assignment
    @Description    : This BSO class is used get the details about all the books for a particular publishing house
*/
public class PublisherBooksDetailsClassBSO {
    
    /*
        @Author         : Sidharth Pushp
        @BuildDate      : 22nd April, 2022
        @Description    : Get all books published by the publishing house
        @Params         : String publisherId
        @Return         : List<BooksWithAuthorDetailsWrapper>
    */
    @AuraEnabled
    public static List<BooksWithAuthorDetailsWrapper> fetchBooksToShowOnPublisher( String publisherId ) {
        if ( String.isNotBlank( publisherId )) {
            
            List<BooksWithAuthorDetailsWrapper> booksAuthorDetailsWrapperList = new List<BooksWithAuthorDetailsWrapper>();
            List<BookAuthor__c> booksAuthors = PublisherBooksDetailsClassDAO.getBooksOnPublisher( publisherId );
            
            if ( booksAuthors != null && !booksAuthors.isEmpty() ) {
                for ( BookAuthor__c bookAuthor : booksAuthors ) {
                    booksAuthorDetailsWrapperList.add(
                        new BooksWithAuthorDetailsWrapper( 
                            bookAuthor.Book__r.Name , bookAuthor.Book__r.Genre__c , bookAuthor.Book__r.Language__c , 
                            bookAuthor.Book__r.PublishingDate__c, bookAuthor.Author__c , 
                            bookAuthor.Author__r.FirstName__c + ' ' + bookAuthor.Author__r.LastName__c                
                        )
                    );
                }
                return booksAuthorDetailsWrapperList;
            }
        }
        return null;
    }

    /*
        @Author         : Sidharth Pushp
        @BuildDate      : 222nd April, 2022
        @Description    : Wrapper class for sending books details along with Author details
    */
    public class BooksWithAuthorDetailsWrapper {

        @AuraEnabled public String bookName     { get; set; }
        @AuraEnabled public String genre        { get; set; }
        @AuraEnabled public String language     { get; set; }
        @AuraEnabled public Date publishDate    { get; set; }
        @AuraEnabled public String authorId     { get; set; }
        @AuraEnabled public String authorName   { get; set; }

        public BooksWithAuthorDetailsWrapper( String bookName , String genre , String language , Date publishDate , 
                                              String authorId , String authorName ) {
            this.bookName = bookName;
            this.genre = genre;
            this.language = language;
            this.publishDate = publishDate;
            this.authorId = authorId;
            this.authorName = authorName;
        }
    }
}